fhir_prem_to_decision:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('AN_DB_HOST', 'analytics-db') }}"
      port: "{{ env_var('AN_DB_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_USER', 'dbt_user') }}"
      password: "{{ env_var('DBT_PASSWORD', 'dbt_password') }}"
      dbname: "{{ env_var('AN_DB_NAME', 'analytics') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'stg') }}"
      threads: 4
